version     = "0.0.0"
author      = "Andre von Houck"
description = "Description of your library"
license     = "MIT"

srcDir = "src"

requires "nim >= 1.2.2"
requires "pixie#head"
requires "vmath#head"
requires "print#head"
requires "opengl >= 1.2.3"
requires "staticglfw >= 4.1.2"
requires "cligen >= 1.0.0"
requires "jsony#head"
requires "puppy#head"
