version     = "0.0.0"
author      = "Andre von Houck"
description = "Description of your library"
license     = "MIT"

srcDir = "src"

requires "nim >= 1.2.2"
requires "typography >= 0.7.10"
requires "pixie >= 1.1.2"
requires "print >= 0.1.0"
requires "opengl >= 1.2.3"
requires "staticglfw >= 4.1.2"
requires "cligen >= 1.0.0"
requires "jsony >= 1.0.0"
requires "puppy >= 1.0.1"
